name: Deploy Static Website

on:
  push:
    branches: [ "main" ]

permissions:
  contents: read
  pages: write
  id-token: write

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4

      - name: Upload website files
        uses: actions/upload-pages-artifact@v4
        with:
          path: .  # <-- deploy everything in the repo (HTML/CSS/JS)

      - name: Deploy to GitHub Pages
        uses: actions/deploy-pages@v4
